/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pruebacochebean;

import componente.Coche;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author josegomez
 */
public class CocheSearchPanel extends javax.swing.JPanel {

    private ArrayList<Coche> coches;

    /**
     * Creates new form CocheSearchPanel
     */
    public CocheSearchPanel() {
        initComponents();

        //Recibimos la instancia de los coches
        coches = CocheSingleton.getInstance().getCoches();
        //Y comprobamos sobre qué está el foco
        checkFocus();

        // Crea un componente invisible y solicita el foco
        JComponent invisible = new JComponent() {
        };

        //Añadimos el componente al panel
        this.add(invisible);

        //Vamos a usar un hilo vacío para darle cierta espera al componente
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //Pedimos que contenga el foco y así el texto no lo tendrá y por lo tanto, mostrará
                //Lo que seleccionamos como "pista"
                invisible.requestFocusInWindow();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiLupa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        etiLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebacochebean/magnifying-glass-icon-26760-20@2x.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Buscador de Coches");

        txtBuscar.setText("Escriba la matrícula del coche a buscar");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiLupa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiLupa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String busqueda = txtBuscar.getText();
        Coche coche = buscarCoche(busqueda);
        if (coche != null) {
            StringBuilder sb = new StringBuilder();
            sb.append("Matricula: ").append(coche.getMatricula())
                    .append(", Marca: ").append(coche.getMarca())
                    .append(", Modelo: ").append(coche.getModelo())
                    .append(", Kilometros: ").append(coche.getKilometros())
                    .append(", Año de Matriculación: ").append(coche.getAnoMatriculacion())
                    .append("\n\n");

            JOptionPane.showMessageDialog(this, sb, "Coche encontrado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el coche", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    //El método CheckFocus comprobará DONDE está el foco de la aplicación, y como por defecto lo colocamos en
    //Un componente invisible realizará su comportamiento
    public void checkFocus() {
        //Usará un FocusListener que "escuchará" dónde está el foco. 
        txtBuscar.addFocusListener(new FocusListener() {

            //Cuando se gane el foco, si el texto es el por defecto (TextHint) lo vaciará.
            @Override
            public void focusGained(FocusEvent e) {
                if (txtBuscar.getText().equals("Escriba la matrícula del coche a buscar")) {
                    txtBuscar.setText("");
                }
            }

            //Cuando se pierda el foco, si se ha borrado todo y se pulsa en "buscar", devolverá
            //El texto a la pista.
            @Override
            public void focusLost(FocusEvent e) {
                if (txtBuscar.getText().equals("")) {
                    txtBuscar.setText("Escriba la matrícula del coche a buscar");
                }
            }
        });
    }

    //Método para buscar coches
    public Coche buscarCoche(String matricula) {
        for (Coche coche : coches) {
            if (coche.getMatricula().equals(matricula)) {
                return coche;
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel etiLupa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
