package pruebacochebean;

import componente.Coche;
import java.util.ArrayList;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author josegomez
 */
public class Concesionario extends javax.swing.JDialog {

    private static ArrayList<Coche> coches;
    private static Concesionario instance;

    /**
     * Creates new form Concesionario
     */
    public Concesionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        instance = this;
        coches = CocheSingleton.getInstance().getCoches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddCoche = new javax.swing.JButton();
        btnDelCoche = new javax.swing.JButton();
        btnShowCoches = new javax.swing.JButton();
        btnSearchByPlate = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        jLabel1.setText("COCHES USADOS FULANITO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebacochebean/Captura de pantalla 2024-03-07 a las 17.42.00.png"))); // NOI18N

        jLabel3.setText("Los mejores coches a este lado del Mississippi");

        jLabel4.setText("Gestión de la BD");

        jLabel5.setText("Consultas");

        btnAddCoche.setText("Añadir Coche");
        btnAddCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCocheActionPerformed(evt);
            }
        });

        btnDelCoche.setText("Eliminar Coche");
        btnDelCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCocheActionPerformed(evt);
            }
        });

        btnShowCoches.setText("Mostrar Coches");
        btnShowCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCochesActionPerformed(evt);
            }
        });

        btnSearchByPlate.setText("Buscar Por Matrícula");
        btnSearchByPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByPlateActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel3)))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCoche)
                    .addComponent(btnDelCoche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnShowCoches)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearchByPlate)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCoche)
                    .addComponent(btnShowCoches))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchByPlate)
                    .addComponent(btnDelCoche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCocheActionPerformed
        AddCocheDialog dialog = new AddCocheDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddCocheActionPerformed

    private void btnDelCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCocheActionPerformed
        String matricula = JOptionPane.showInputDialog(this, "Introduce la matrícula del coche a eliminar");
        if (matricula != null && !matricula.isEmpty()) {
            Coche cocheAEliminar = null;
            for (Coche coche : coches) {
                if (coche.getMatricula().equals(matricula)) {
                    cocheAEliminar = coche;
                    break;
                }
            }
            if (cocheAEliminar != null) {
                coches.remove(cocheAEliminar);
                CocheSingleton.getInstance().delCoche(matricula); // Llamada al método delCoche
                JOptionPane.showMessageDialog(this, "Coche eliminado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un coche con la matrícula introducida");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes introducir una matrícula");
        }

    }//GEN-LAST:event_btnDelCocheActionPerformed

    private void btnShowCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCochesActionPerformed
        StringBuilder sb = new StringBuilder();
        for (Coche coche : coches) {
            sb.append("Matricula: ").append(coche.getMatricula())
                    .append(", Marca: ").append(coche.getMarca())
                    .append(", Modelo: ").append(coche.getModelo())
                    .append(", Kilometros: ").append(coche.getKilometros())
                    .append(", Año de Matriculación: ").append(coche.getAnoMatriculacion())
                    .append("\n\n");
        }
        JTextArea textArea = new JTextArea(sb.toString());
        JScrollPane scrollPane = new JScrollPane(textArea);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        scrollPane.setPreferredSize(new Dimension(500, 500));
        JOptionPane.showMessageDialog(this, scrollPane, "Lista de coches", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnShowCochesActionPerformed

    private void btnSearchByPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByPlateActionPerformed
        CocheSearchPanel panel = new CocheSearchPanel();

        JDialog dialog = new JDialog(this, "Buscar coche por matrícula", true);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSearchByPlateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.out.println("Saliendo...");
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concesionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concesionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concesionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concesionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Concesionario dialog = new Concesionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ArrayList<Coche> getCoches() {
        return coches;
    }

    public static Concesionario getInstance() {
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCoche;
    private javax.swing.JButton btnDelCoche;
    private javax.swing.JButton btnSearchByPlate;
    private javax.swing.JButton btnShowCoches;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
